### ISSUE TITLE
Can we update this to the latest, please?

### ISSUE THREAD

**Issue by frederikhors** [michidk/choco#1]
Can we update this to the latest, please?

Can we make this process automatic?

**Comment by michidk** [comment]
I just pushed 1.1.3: https://community.chocolatey.org/packages/just/1.1.3 in https://github.com/michidk/just-choco/commit/d6d9ffdc871cdb540a1c7bd55676c3e58d3fd327

With some effort, this could be automated for sure. I found this repo https://github.com/sitiom/chocolatey-packages, which runs a GitHub workflow daily and checks the GitHub releases to then adjust the version and hash and finally create a choco package. Could be a good starting point to implement that.

**Comment by michidk** [comment]
I restructured this repo to now be a monorepo with all my choco packages that automatically update the packages in the Choco registry thanks to the GitHub CI.
