### ISSUE TITLE
Typst not installed correctly

### ISSUE THREAD

**Issue by ptsouchlos** [michidk/choco#2]
It seems that `typst` is not installed correctly when running `choco install typst`. It downloads the zip folder in the `C:\programdata\chocolatey\lib\typst\tools` correctly, but the typst executable is never extracted and installed in a common location (i.e. `C:\ProgramData\chocolatey\bin`.

**Comment by michidk** [comment]
Thanks for reporting this! You are right, the .zip was never installed. This should be fixed now. Waiting for the chocolatey team to approve the new version.

**Comment by ptsouchlos** [comment]
Thanks for the fix!
